[package]
name = "typst-ts-mode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
two-face = { version = "0.3.0", default-features = false, features = ["syntect-fancy"] }
