;;; typst-ts-embedding-lang-settings.el --- Embedding Languages Settings  -*- lexical-binding: t; -*-
;; Copyright (C) 2023-2024 The typst-ts-mode Project Contributors

;; This file is NOT part of Emacs.
;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; Functionality to embed other languages in typst documentation.

;;; Code:
(require 'treesit)
(require 'typst-ts-core)

;; Generated by `cargo-run'
;; We here use print expression to create hash table, see `(elisp) Creating Hash'
(defvar typst-ts-els-tag-lang-map
  #s(hash-table
     size 588
     test equal
     data
     (
      "txt" txt "asa" asp "asp" asp
      "as" actionscript "actionscript" actionscript "script editor" applescript
      "applescript" applescript "cmd" bat "bat" bat
      "build" build "cs" c-sharp "csx" c-sharp
      "c#" c-sharp "hpp" c++ "c++" c++
      "hh" c++ "h++" c++ "inl" c++
      "cp" c++ "cpp" c++ "cxx" c++
      "ipp" c++ "cc" c++ "hxx" c++
      "c" c "css.liquid" css "css" css
      "css.erb" css "edn" clojure "clj" clojure
      "cljs" clojure "cljc" clojure "clojure" clojure
      "d" d "di" d "diff" diff
      "patch" diff "erl" erlang "hrl" erlang
      "emakefile" erlang "erlang" erlang "escript" erlang
      "yaws" yaws "gitattributes" attributes ".gitattributes" attributes
      "attributes" attributes "tag_editmsg" commit_editmsg "merge_msg" commit_editmsg
      "commit_editmsg" commit_editmsg "gitconfig" gitconfig ".gitconfig" gitconfig
      ".gitmodules" gitconfig "gitignore" exclude "exclude" exclude
      ".gitignore" exclude ".git" .git "gitlog" gitlog
      ".mailmap" .mailmap "mailmap" .mailmap "git-rebase-todo" git-rebase-todo
      "go" go "dot" dot "gv" dot
      "gradle" groovy "groovy" groovy "jenkinsfile" groovy
      "gvy" groovy "shtml" html "xhtml" html
      "htm" html "html" html "haskell" haskell
      "hs" haskell "lhs" lhs "sublime-settings" json
      "sublime-mousemap" json "sublime-color-scheme" json "pipfile.lock" json
      "sublime-build" json "sublime-commands" json "sublime-completions" json
      "sublime-theme" json "json" json "sublime-project" json
      "sublime-keymap" json "sublime-macro" json "sublime-menu" json
      "ipynb" json "jsp" jsp "bsh" java
      "java" java "javadoc" javadoc "properties" properties
      "js" js "javascript" js "htc" js
      "bibtex" bibtex "bib" bibtex "latex" latex
      "ltx" latex "tex" tex "cls" tex
      "sty" tex "clisp" common-lisp "el" lisp
      "lsp" lisp "fasl" lisp "lisp" lisp
      "cl" lisp "scm" lisp "l" lisp
      "mud" lisp "ss" lisp "lua" lua
      "makefile" makefile "mak" makefile "mk" makefile
      "gnumakefile" makefile "make" makefile "makefile.in" makefile
      "makefile.am" makefile "ocamlmakefile" makefile "mdown" markdown
      "markdn" markdown "markdown" markdown "md" markdown
      "multimarkdown" multimarkdown "matlab" matlab "mli" ocaml
      "ml" ocaml "ocaml" ocaml "mll" ocamllex
      "ocamllex" ocamllex "mly" ocamlyacc "ocamlyacc" ocamlyacc
      "camlp4" camlp4 "objective-c++" objective-c++ "mm" objective-c++
      "h" objective-c "m" objective-c "objective-c" objective-c
      "php3" php "phps" php "phpt" php
      "php5" php "php" php "php4" php
      "phtml" php "php7" php "pas" pascal
      "dpr" pascal "p" pascal "pascal" pascal
      "pod" perl "pl" perl "pmc" perl
      "pc" perl "t" perl "pm" perl
      "perl" perl "gypi" python "bzl" python
      "sconscript" python "py" python "pxi" python
      "pyx.in" python "vpy" python "pxd.in" python
      "pyw" python "py3" python "pyx" python
      "cpy" python "wscript" python "rpy" python
      "sconstruct" python "gyp" python "snakefile" python
      "bazel" python "python" python "pxd" python
      "pyi" python "pxi.in" python "rprofile" r
      "r" r "rd" rd "erb" rails
      "rhtml" rails "html.erb" rails "rails" rails
      "js.erb" js.erb "sass" haml "haml" haml
      "rxml" rxml "builder" rxml "erbsql" erbsql
      "sql.erb" erbsql "re" re "rst" restructuredtext
      "rest" restructuredtext "restructuredtext" restructuredtext "fastfile" ruby
      "guardfile" ruby "rantfile" ruby "podspec" ruby
      "capfile" ruby "berksfile" ruby "rake" ruby
      "rakefile" ruby "fcgi" ruby "irbrc" ruby
      "cheffile" ruby "scanfile" ruby "prawn" ruby
      "cgi" ruby "config.ru" ruby "appfile" ruby
      "jbuilder" ruby "rb" ruby "rabl" ruby
      "gemspec" ruby "ruby" ruby "rjs" ruby
      "rbx" ruby "vagrantfile" ruby "thor" ruby
      "podfile" ruby "gemfile" ruby "snapfile" ruby
      "brewfile" ruby "simplecov" ruby "ruby.rail" ruby
      "deliverfile" ruby "appraisals" ruby "thorfile" ruby
      "rs" rust "rust" rust "ddl" sql
      "dml" sql "sql" sql "sbt" scala
      "sc" scala "scala" scala "sh" bash
      ".zshrc" bash "eclass" bash ".zprofile" bash
      "zsh" bash ".profile" bash ".bash_functions" bash
      ".bash_completions" bash ".zlogin" bash ".zshenv" bash
      "ebuild" bash ".bash_logout" bash ".bash_login" bash
      "ash" bash ".bash_profile" bash ".bash_variables" bash
      ".bashrc" bash ".textmate_init" bash ".bash_aliases" bash
      "pkgbuild" bash ".zlogout" bash "bash" bash
      "shell-unix-generic" shell-unix-generic "commands-builtin-shell-bash" commands-builtin-shell-bash "adp" adp
      "tcl" tcl "textile" textile "tld" xml
      "xsd" xml "dtml" xml "rss" xml
      "rng" xml "opml" xml "xaml" xml
      "xml" xml "xslt" xml "svg" xml
      "yaml" yaml "yml" yaml "sublime-syntax" yaml
      "awk" awk "ada" ada "adb" ada
      "ads" ada "gpr" ada ".htgroups" envvars
      "envvars" envvars ".htpasswd" envvars ".htaccess" envvars
      "htgroups" envvars "htaccess" envvars "htpasswd" envvars
      "ad" adoc "asciidoc" adoc "adoc" adoc
      "asm" yasm "nasm" yasm "yasm" yasm
      "inc" yasm "mac" yasm "h.in" h.in
      "hh.in" hh.in "h++.in" hh.in "hxx.in" hh.in
      "hpp.in" hh.in "cmakelists.txt" cmake "cmake" cmake
      "cmakecache.txt" cmakecache "cmakecache" cmakecache "cmakecommands" cmakecommands
      "csv" csv "tsv" csv "cabal" cabal
      "cson" coffeescript "coffeescript" coffeescript "coffee.erb" coffeescript
      "coffee" coffeescript "cakefile" coffeescript "cpuinfo" cpuinfo
      "crontab" crontab "tab" crontab "cron.d" crontab
      "cr" crystal "crystal" crystal "dart" dart
      "dockerfile" dockerfile ".env.test" dotenv ".env.test.local" dotenv
      ".env.production.local" dotenv "env.template" dotenv "env.sample" dotenv
      "dotenv" dotenv ".env.testing" dotenv "env" dotenv
      ".env.sample" dotenv ".env.template" dotenv ".env.staging" dotenv
      ".env.defaults" dotenv "env.example" dotenv ".env.local" dotenv
      ".env.development" dotenv ".env.dusk.local" dotenv ".env.development.local" dotenv
      ".env.default" dotenv ".env.example" dotenv ".envrc" dotenv
      ".flaskenv" dotenv ".env.dist" dotenv ".env" dotenv
      ".env.production" dotenv ".env.prod" dotenv ".env.dev" dotenv
      "elixir" elixir "exs" elixir "ex" elixir
      "html.leex" html.eex "html.eex" html.eex "elm" elm
      "eml" email "mbx" email "msg" email
      "mboxz" email "email" email "f#" fs
      "fsi" fs "fsx" fs "fish" fish
      "f77" f "for" f "fpp" f
      "f" f "f08" f90 "f95" f90
      "f03" f90 "f90" f90 "namelist" namelist
      "fstab" fstab "crypttab" fstab "mtab" fstab
      "frag" glsl "mesh" glsl "glsl" glsl
      "vs" glsl "tesc" glsl "rmiss" glsl
      "fsh" glsl "vshader" glsl "task" glsl
      "rchit" glsl "fshader" glsl "rgen" glsl
      "fs" glsl "gshader" glsl "vsh" glsl
      "geom" glsl "gs" glsl "rahit" glsl
      "comp" glsl "tese" glsl "rcall" glsl
      "rint" glsl "vert" glsl "gsh" glsl
      "gql" graphql "graphql" graphql "graphqls" graphql
      "2" groff/troff "groff" groff/troff "8" groff/troff
      "7" groff/troff "4" groff/troff "5" groff/troff
      "6" groff/troff "1" groff/troff "9" groff/troff
      "troff" groff/troff "groff/troff" groff/troff "3" groff/troff
      "group" group "twig" twig "html.twig" twig
      "hosts" hosts "cfg" ini ".coveragerc" ini
      "hgrc" ini ".gitlint" ini ".hgrc" ini
      "desktop" ini ".editorconfig" ini ".pylintrc" ini
      "inf" ini "ini" ini "reg" ini
      "lng" ini "url" ini "xhtml.j2" htm.j2
      "html.j2" htm.j2 "htm.j2" htm.j2 "xml.j2" htm.j2
      "jinja" jinja2 "j2" jinja2 "jinja2" jinja2
      "libsonnet" jsonnet "libjsonnet" jsonnet "jsonnet" jsonnet
      "jl" julia "julia" julia "kts" kotlin
      "kt" kotlin "kotlin" kotlin "less" less
      "css.less" less "ll" llvm "llvm" llvm
      "lean" lean "manpage" manpage "man" manpage
      "mediawikerpanel" mediawikerpanel "wikipedia" mediawiki "wiki" mediawiki
      "mediawiki" mediawiki "meminfo" meminfo "scgi_params" nginx
      "uwsgi_params" nginx "nginx" nginx "fastcgi_params" nginx
      "nginx.conf" nginx "conf" nginx "conf.erb" nginx
      "mime.types" nginx "nim" nim "nims" nim
      "nimble" nim "ninja" ninja "nix" nix
      "orgmode" orgmode "org" orgmode "passwd" passwd
      "proto" proto "protodevel" proto "proto.text" pb.txt
      "textpb" pb.txt "prototxt" pb.txt "pb.txt" pb.txt
      "pbtxt" pb.txt "puppet" puppet "epp" puppet
      "pp" puppet "purescript" purescript "purs" purescript
      "qml" qml "qmlproject" qml "rkt" racket
      "racket" racket "rego" rego "requirements.in" requirements.txt
      "requirements.txt" requirements.txt "pip" requirements.txt "resolv.conf" resolv
      "resolv" resolv "resource" robot "robot" robot
      "scss" scss "sml" sml "sig" sml
      "cm" sml "skim" slim "slim" slim
      "strace" strace "styl" stylus "stylus" stylus
      "solidity" solidity "sol" solidity "vy" vyper
      "vyper" vyper "jq" jq "svelte" svelte
      "svlt" svelte "swift" swift "svh" systemverilog
      "sv" systemverilog "vh" systemverilog "systemverilog" systemverilog
      "toml" toml "cargo.lock" toml "gopkg.lock" toml
      "tml" toml "pipfile" toml "poetry.lock" toml
      "pdm.lock" toml "tfstate" tfstate "terraform" terraform
      "tf" terraform "hcl" terraform "tfvars" terraform
      "done.txt" todo.txt "todo.txt" todo.txt "ts" typescript
      "cts" typescript "typescript" typescript "mts" typescript
      "typescriptreact" typescriptreact "tsx" typescriptreact "v" verilog
      "verilog" verilog "vim" viml "gvimrc" viml
      "_vimrc" viml ".vimrc" viml "_gvimrc" viml
      "viml" viml "vimrc" viml ".gvimrc" viml
      "vue" vue "zig" zig "plot" gnuplot
      "gp" gnuplot "gnuplot" gnuplot "plt" gnuplot
      "gnu" gnuplot "gpl" gnuplot "http" http
      "log" log "show-nonprintable" show-nonprintable "authorized_keys2" authorized_keys
      "authorized_keys" authorized_keys "pub" authorized_keys "known_hosts" known_hosts
      "known_hosts.old" known_hosts "ssh_config" ssh_config "sshd_config" sshd_config
      "syslog" syslog "varlink" varlink "typc" typst
      "typst" typst "typ" typst
      ))
  "Raw block tag -> tree sitter language map.")


;; refer to markdown-get-lang-mode
(defun typst-ts-els-get-lang-mode (lang)
  "Return major mode that should be used for LANG.
LANG is a string, and the returned major mode is a symbol."
  (let ((lang-norm (downcase lang)))
    (cl-find-if
     #'(lambda (mode) (and mode (fboundp mode)))
     (list
      (and (treesit-language-available-p (intern lang-norm))
           (intern (concat lang-norm "-ts-mode")))
      (intern (concat lang-norm "-mode"))))))

;; refer to `markdown-fontify-code-block-natively'
(defun typst-ts-els-fontify-raw-block (lang-mode start end)
  "Fontify a raw block using traditional approach.
LANG-MODE START END."
  (let ((string (buffer-substring-no-properties start end))
        (modified (buffer-modified-p))
        (typst-doc-buffer (current-buffer)) pos next)
    (remove-text-properties start end '(face nil))
    (with-current-buffer
        (get-buffer-create
         (concat " *typst-raw_blck-fontification:" (symbol-name lang-mode)))
      ;; Make sure that modification hooks are not inhibited in
      ;; the org-src-fontification buffer in case we're called
      ;; from `jit-lock-function' (Bug#25132).
      (let ((inhibit-modification-hooks nil))
        (delete-region (point-min) (point-max))
        (insert string " ")) ;  so there's a final property change
      (unless (eq major-mode lang-mode) (funcall lang-mode))
      (font-lock-ensure)
      (setq pos (point-min))
      (while (setq next (next-single-property-change pos 'face))
        (let ((val (get-text-property pos 'face)))
          (when val
            (put-text-property
             (+ start (1- pos)) (1- (+ start next)) 'face
             val typst-doc-buffer)))
        (setq pos next)))
    (set-buffer-modified-p modified)))

(provide 'typst-ts-embedding-lang-settings)

;;; typst-ts-embedding-lang-settings.el ends here
